### PR TITLE
Microverse Hello Project

### PR DESCRIPTION
**Pull request by batoorsohail**
## Hello World project: 

In this project we added:
-HTML file with the text Hello Microverse!
-CSS file with the color Blue

### CODE REVIEW

**Review by cwaku — CHANGES_REQUESTED** [review]
Hi @batoorsohail 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
There are a few issues 🐛  that you still need to work 🛠️  on to go to the next project ⏭️, but you are almost there! 🏃🏾 

## Highlights
 - [x] Correct GitHub Flow 👍🏾 
 - [x] Good commit history 🥇 
 - [x] Good PR title/description 💯 
 - [x] All linters passed 🥇 

## Required Changes ♻️
It's ok to have bugs in your code. Please, see this code review as a chance to learn practical coding skills and new tips 🌟  that can improve your code quality 💯 and help you get a better job 💼.

I will guide 📔 you through fixing 🛠️ these bugs, follow my comments down below and make sure you don't miss any of them to get your project approved ✅

- [ ] For a more professional repo, kindly update your README.md file to match the [README template](https://github.com/microverseinc/readme-template/blob/master/README.md)
- [ ] The Pull Request should have a short summary describing introduced changes in more detail. Kindly fix that.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by cwaku — COMMENTED** [review]
Kindly resubmit through the dashboard when you are done with the changes required.

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @batoorsohail, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* Good commit messages. :heavy_check_mark:
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:
* PR has a good summary :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] As suggested by the previous reviewer, I kindly suggest that you update your [README](https://github.com/microverseinc/readme-template) in your repo, using the Microverse [template](https://github.com/microverseinc/readme-template) as this will give users detailed information about your project.
- [ ] Please remember to personalize your README file content and put your project information there.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- [ ] Next time, and for future Pull Requests, please kindly add a descriptive PR title as seen in the demo below:
pull_request_desc

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by batoorsohail** [comment]
Hi @topeogunleye,
Thanks for your review.
I have a question should I add the README template to the main branch or to the htmlcss branch.

**Review by Lizdev-05 — APPROVED** [review]
Hi @batoorsohail, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966

## Highlights

- Correct GitHub Flow 👍🏾
- Good commit history 🥇
- Good PR title/description 💯
- All linters passed 🥇
- Personalized README file ✔
## Optional suggestions
[OPTIONAL] As suggested by the previous reviewer, Next time, and for future Pull Requests, please kindly add a descriptive PR title as seen in the demo below:

summ

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
> Hi @topeogunleye, Thanks for your review. I have a question should I add the README template to the main branch or to the htmlcss branch.

@batoorsohail, Changes are to always be made to the current branch in review i.e `htmlcss` branch .

**Pull request merged**
